[package]
name = "vulkano-rangemap"
version = "1.0.3"
authors = ["Jeff Parsons <jeff@parsons.io>"]
edition = "2018"
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/vulkano-rs/rangemap"
documentation = "https://docs.rs/vulkano-rangemap"
homepage = "https://github.com/vulkano-rs/rangemap"
description = """
Map and set data structures whose keys are stored as ranges.

Contiguous and overlapping ranges that map to the same value are coalesced into a single range.
"""
categories = ["data-structures"]

[dependencies]
serde = { version = "1", optional = true }

[dev-dependencies]
permutator = "0.4"
criterion = "0.3"
rand = "0.8"
chrono = "0.4" # For examples
rustc_version = "0.4"
serde_json = "1"

[features]
serde1 = ["serde"]
# So we can run doc tests from "README.md".
nightly = []

[[bench]]
name = "kitchen_sink"
harness = false
